version: '3.4'

networks:
  Template_NET_5_WORKER.CoreService:

services:
  Template_NET_5_worker.coreservice:
    image: ${DOCKER_REGISTRY-}templatenet5workercoreservice
    build:
      context: .
      dockerfile: src/Template_NET_5_WORKER.CoreService/Dockerfile
    networks:
     - Template_NET_5_WORKER.CoreService
  rabbitmq:
    hostname: rabbit
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks:
     - Template_NET_5_WORKER.CoreService
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
    healthcheck:
        timeout: 5s
        interval: 5s
        retries: 10
        test:
          - "CMD"
          - "rabbitmqctl"
          - "status" 
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    networks:
      - Template_NET_5_WORKER.CoreService
    ports:
      - '27017-27019:27017-27019'